#! /usr/bin/python3
import sys

def isprime(n):
    for i in range(2,n//2):
        if(n%i)==0:
            return False
            break
    return True

def factors():
    """traverse through a file and find factors for each number"""
    try:
        with open(sys.argv[1]) as f:
            for line in f:
                line = int(line)
                for i in range (2,  line + 1):
                    if line%i ==0:
                        if isprime(line//i) and isprime(i):
                            print(f"{line}={line//i}*{i}")
                            break
                        else:
                            continue
    except(IndexError):
        print("No argurments passed")
factors()

